name: .NET testing action

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Opening mongo_docker dir
      run: cd mongo_docker

    - name: Run mongodb docker instance
      run:  chmod +x ./run_local_mongodb && ./run_local_mongodb

    - name: Test
      run: dotnet test --no-build --verbosity normal

